


CREATE VIEW [dbo].[RESULTVIEWSTAT]
AS
SELECT        D.DESCRIPTION AS EXPERIMENT, D.EXPERIMENTID AS EXPERIMENTID, E.NAME AS DATASET, F.NAME AS IDENTIFICATION, F.NAMEALIAS AS IDENTIFICATIONALIAS, G.NAME AS VOTING, G.NAMEALIAS AS VOTINGALIAS, H.NAME AS WEIGHTING, 
                         H.NAMEALIAS AS WEIGHTINGALIAS, I.NAME AS MODEL, I.NAMEALIAS AS MODELALIAS, J.NAME AS EXCEPTION, J.NAMEALIAS AS EXCEPTIONALIAS, C.EPSILON, C.ENSEMBLESIZE, C.AVGACCURACY, 
                         C.MINACCURACY, C.MAXACCURACY, C.DEVACCURACY, C.VARACCURACY, C.AVGBALANCEDACCURACY, C.MINBALANCEDACCURACY, C.MAXBALANCEDACCURACY, C.DEVBALANCEDACCURACY, 
                         C.VARBALANCEDACCURACY, C.AVGCONFIDENCE, C.MINCONFIDENCE, C.MAXCONFIDENCE, C.DEVCONFIDENCE, C.VARCONFIDENCE, C.AVGCOVERAGE, C.MINCOVERAGE, C.MAXCOVERAGE, C.DEVCOVERAGE, 
                         C.VARCOVERAGE, C.AVGREDUCTLEN, C.MINREDUCTLEN, C.MAXREDUCTLEN, C.DEVREDUCTLEN, C.VARREDUCTLEN, C.AVGEXCEPTIONRULEHITCOUNTER, C.AVGEXCEPTIONRULELENGTHSUM, 
                         C.AVGSTANDARDRULEHITCOUNTER, C.AVGSTANDARDRULELENGTHSUM, C.MINEXCEPTIONRULEHITCOUNTER, C.MINEXCEPTIONRULELENGTHSUM, C.MINSTANDARDRULEHITCOUNTER, 
                         C.MINSTANDARDRULELENGTHSUM, C.MAXEXCEPTIONRULEHITCOUNTER, C.MAXEXCEPTIONRULELENGTHSUM, C.MAXSTANDARDRULEHITCOUNTER, C.MAXSTANDARDRULELENGTHSUM
FROM            (SELECT        EXPERIMENTID, DATASETID, MODELTYPEID, WEIGHTINGTYPEID, EXCEPTIONRULETYPEID, IDENTIFICATIONTYPEID, VOTINGTYPEID, ENSEMBLESIZE, EPSILON, AVG(ACCURACY) 
                                                    AS AVGACCURACY, AVG(BALANCEDACCURACY) AS AVGBALANCEDACCURACY, AVG(CONFIDENCE) AS AVGCONFIDENCE, AVG(COVERAGE) AS AVGCOVERAGE, AVG(REDUCTLEN) AS AVGREDUCTLEN, 
                                                    MIN(ACCURACY) AS MINACCURACY, MIN(BALANCEDACCURACY) AS MINBALANCEDACCURACY, MIN(CONFIDENCE) AS MINCONFIDENCE, MIN(COVERAGE) AS MINCOVERAGE, MIN(REDUCTLEN) 
                                                    AS MINREDUCTLEN, MAX(ACCURACY) AS MAXACCURACY, MAX(BALANCEDACCURACY) AS MAXBALANCEDACCURACY, MAX(CONFIDENCE) AS MAXCONFIDENCE, MAX(COVERAGE) AS MAXCOVERAGE, 
                                                    MAX(REDUCTLEN) AS MAXREDUCTLEN, STDEVP(ACCURACY) AS DEVACCURACY, STDEVP(BALANCEDACCURACY) AS DEVBALANCEDACCURACY, STDEVP(CONFIDENCE) AS DEVCONFIDENCE, 
                                                    STDEVP(COVERAGE) AS DEVCOVERAGE, STDEVP(REDUCTLEN) AS DEVREDUCTLEN, VARP(ACCURACY) AS VARACCURACY, VARP(BALANCEDACCURACY) AS VARBALANCEDACCURACY, 
                                                    VARP(CONFIDENCE) AS VARCONFIDENCE, VARP(COVERAGE) AS VARCOVERAGE, VARP(REDUCTLEN) AS VARREDUCTLEN, AVG(EXCEPTIONRULEHITCOUNTER) AS AVGEXCEPTIONRULEHITCOUNTER, 
                                                    AVG(EXCEPTIONRULELENGTHSUM) AS AVGEXCEPTIONRULELENGTHSUM, AVG(STANDARDRULEHITCOUNTER) AS AVGSTANDARDRULEHITCOUNTER, AVG(STANDARDRULELENGTHSUM) 
                                                    AS AVGSTANDARDRULELENGTHSUM, MIN(EXCEPTIONRULEHITCOUNTER) AS MINEXCEPTIONRULEHITCOUNTER, MIN(EXCEPTIONRULELENGTHSUM) AS MINEXCEPTIONRULELENGTHSUM, 
                                                    MIN(STANDARDRULEHITCOUNTER) AS MINSTANDARDRULEHITCOUNTER, MIN(STANDARDRULELENGTHSUM) AS MINSTANDARDRULELENGTHSUM, MAX(EXCEPTIONRULEHITCOUNTER) 
                                                    AS MAXEXCEPTIONRULEHITCOUNTER, MAX(EXCEPTIONRULELENGTHSUM) AS MAXEXCEPTIONRULELENGTHSUM, MAX(STANDARDRULEHITCOUNTER) AS MAXSTANDARDRULEHITCOUNTER, 
                                                    MAX(STANDARDRULELENGTHSUM) AS MAXSTANDARDRULELENGTHSUM
                          FROM            (SELECT        EXPERIMENTID, TESTID, DATASETID, MODELTYPEID, WEIGHTINGTYPEID, EXCEPTIONRULETYPEID, IDENTIFICATIONTYPEID, VOTINGTYPEID, ENSEMBLESIZE, EPSILON, 
                                                                              AVG(ACCURACY) AS ACCURACY, AVG(BALANCEDACCURACY) AS BALANCEDACCURACY, AVG(CONFIDENCE) AS CONFIDENCE, AVG(COVERAGE) AS COVERAGE, 
                                                                              AVG(AVERAGEREDUCTLENGTH) AS REDUCTLEN, AVG(EXCEPTIONRULEHITCOUNTER) AS EXCEPTIONRULEHITCOUNTER, AVG(EXCEPTIONRULELENGTHSUM) 
                                                                              AS EXCEPTIONRULELENGTHSUM, AVG(STANDARDRULEHITCOUNTER) AS STANDARDRULEHITCOUNTER, AVG(STANDARDRULELENGTHSUM) AS STANDARDRULELENGTHSUM
                                                    FROM            dbo.RESULT AS A
                                                    GROUP BY EXPERIMENTID, TESTID, DATASETID, MODELTYPEID, WEIGHTINGTYPEID, EPSILON, ENSEMBLESIZE, EXCEPTIONRULETYPEID, IDENTIFICATIONTYPEID, VOTINGTYPEID) AS B
                          GROUP BY EXPERIMENTID, DATASETID, MODELTYPEID, WEIGHTINGTYPEID, EPSILON, ENSEMBLESIZE, EXCEPTIONRULETYPEID, IDENTIFICATIONTYPEID, VOTINGTYPEID) AS C INNER JOIN
                         dbo.EXPERIMENT AS D ON D.EXPERIMENTID = C.EXPERIMENTID INNER JOIN
                         dbo.DATASET AS E ON E.DATASETID = C.DATASETID INNER JOIN
                         dbo.DECISIONRULEMEASURE AS F ON F.RULEQUALITYID = C.IDENTIFICATIONTYPEID INNER JOIN
                         dbo.DECISIONRULEMEASURE AS G ON G.RULEQUALITYID = C.VOTINGTYPEID INNER JOIN
                         dbo.WEIGHTINGTYPE AS H ON H.WEIGHTINGTYPEID = C.WEIGHTINGTYPEID INNER JOIN
                         dbo.MODELTYPE AS I ON I.MODELTYPEID = C.MODELTYPEID INNER JOIN
                         dbo.EXCEPTIONRULETYPE AS J ON J.EXCEPTIONTYPEID = C.EXCEPTIONRULETYPEID