CREATE VIEW [dbo].[RESULTVIEW]
WITH SCHEMABINDING
	AS SELECT 
	D.DESCRIPTION AS EXPERIMENT,
	E.NAME AS DATASET,
	F.NAME AS IDENTIFICATION,
	G.NAME AS VOTING,
	H.NAME AS WEIGHTING,
	I.NAME AS MODEL,
	J.NAME AS EXCEPTION,
	C.EPSILON AS EPSILON,
	C.ENSEMBLESIZE AS ENSEMBLESIZE,
	C.ACCURACY AS ACCURACY,
	C.BALANCEDACCURACY AS BALANCEDACCURACY,
	C.CONFIDENCE AS CONFIDENCE,
	C.COVERAGE AS COVERAGE,
	C.REDUCTLEN AS REDUCTLEN
FROM 
	(SELECT 
		B.EXPERIMENTID AS EXPERIMENTID, 	
		B.DATASETID AS DATASETID, 
		B.MODELTYPEID AS MODELTYPEID,
		B.WEIGHTINGTYPEID AS WEIGHTINGTYPEID,
		B.EXCEPTIONRULETYPEID AS EXCEPTIONRULETYPEID, 
		B.IDENTIFICATIONTYPEID AS IDENTIFICATIONTYPEID, 
		B.VOTINGTYPEID AS VOTINGTYPEID,
		B.ENSEMBLESIZE AS ENSEMBLESIZE,	
		B.EPSILON AS EPSILON,
		AVG(B.ACCURACY) AS ACCURACY,
		AVG(B.BALANCEDACCURACY) AS BALANCEDACCURACY,
		AVG(B.CONFIDENCE) AS CONFIDENCE,
		AVG(B.COVERAGE) AS COVERAGE,
		AVG(B.REDUCTLEN) AS REDUCTLEN
	FROM
		(SELECT 
			A.EXPERIMENTID AS EXPERIMENTID, 
			A.TESTID AS TESTID, 
			A.DATASETID AS DATASETID, 
			A.MODELTYPEID AS MODELTYPEID,
			A.WEIGHTINGTYPEID AS WEIGHTINGTYPEID,
			A.EXCEPTIONRULETYPEID AS EXCEPTIONRULETYPEID, 
			A.IDENTIFICATIONTYPEID AS IDENTIFICATIONTYPEID, 
			A.VOTINGTYPEID AS VOTINGTYPEID,
			A.ENSEMBLESIZE AS ENSEMBLESIZE,	
			A.EPSILON AS EPSILON,
			AVG(A.ACCURACY) AS ACCURACY,
			AVG(A.BALANCEDACCURACY) AS BALANCEDACCURACY,
			AVG(A.CONFIDENCE) AS CONFIDENCE,
			AVG(A.COVERAGE) AS COVERAGE,
			AVG(A.AVERAGEREDUCTLENGTH) AS REDUCTLEN
		FROM dbo.RESULT A	
		GROUP BY 
			A.EXPERIMENTID, 
			A.TESTID, 
			A.DATASETID, 
			A.MODELTYPEID, 
			A.WEIGHTINGTYPEID, 
			A.EPSILON, 
			A.ENSEMBLESIZE, 
			A.EXCEPTIONRULETYPEID, 
			A.IDENTIFICATIONTYPEID, 
			A.VOTINGTYPEID ) B
	GROUP BY 
		B.EXPERIMENTID, 
		B.DATASETID, 
		B.MODELTYPEID, 
		B.WEIGHTINGTYPEID, 
		B.EPSILON, 
		B.ENSEMBLESIZE, 
		B.EXCEPTIONRULETYPEID, 
		B.IDENTIFICATIONTYPEID, 
		B.VOTINGTYPEID) C

JOIN dbo.EXPERIMENT AS D ON D.EXPERIMENTID = C.EXPERIMENTID
JOIN dbo.DATASET AS E ON E.DATASETID = C.DATASETID
JOIN dbo.DECISIONRULEMEASURE AS F ON F.RULEQUALITYID = C.IDENTIFICATIONTYPEID
JOIN dbo.DECISIONRULEMEASURE AS G ON G.RULEQUALITYID = C.VOTINGTYPEID
JOIN dbo.WEIGHTINGTYPE AS H ON H.WEIGHTINGTYPEID = C.WEIGHTINGTYPEID
JOIN dbo.MODELTYPE AS I ON I.MODELTYPEID = C.MODELTYPEID
JOIN dbo.EXCEPTIONRULETYPE AS J ON J.EXCEPTIONTYPEID = C.EXCEPTIONRULETYPEID

	
	
	
