CREATE TABLE [dbo].[DECISIONRULEMEASURE] (
    [RULEQUALITYID] INT           NOT NULL,
    [NAME]          NVARCHAR (50) NOT NULL,
    [NAMEALIAS]     NVARCHAR (10) NULL,
    CONSTRAINT [PK_DECISIONRULEMEASURE] PRIMARY KEY CLUSTERED ([RULEQUALITYID] ASC)
);



