CREATE TABLE [dbo].[MODELTYPE] (
    [MODELTYPEID] INT           NOT NULL,
    [NAME]        NVARCHAR (50) NOT NULL,
    [NAMEALIAS]   NVARCHAR (10) NOT NULL,
    CONSTRAINT [PK_MODELTYPE] PRIMARY KEY CLUSTERED ([MODELTYPEID] ASC)
);



