CREATE TABLE [dbo].[WEIGHTINGTYPE] (
    [WEIGHTINGTYPEID] INT           IDENTITY (1, 1) NOT NULL,
    [NAME]            NVARCHAR (50) NOT NULL,
    [NAMEALIAS]       NVARCHAR (10) NOT NULL,
    CONSTRAINT [PK_WEIGHTINGTYPE] PRIMARY KEY CLUSTERED ([WEIGHTINGTYPEID] ASC)
);



